kafka:
  image: kafka-new
  ports:
    - "9092:9092"
  external_links:
    - storm_zookeeper_1:zk  
  environment:
    KAFKA_ADVERTISED_HOST_NAME: 192.168.59.100
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
